apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: travelduty
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
      - name: api-gateway
        image: travelduty/api-gateway:2.2.5
        ports:
        - containerPort: 7444
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
