apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: travelduty
spec:
  replicas: 5
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
      - name: api-gateway
        image: travelduty/api-gateway:1.5.5
        ports:
        - containerPort: 6726
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
