apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: travelduty
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
      - name: api-gateway
        image: travelduty/api-gateway:5.6.1
        ports:
        - containerPort: 4951
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
