apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: travelduty
spec:
  replicas: 3
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
      - name: auth-service
        image: travelduty/auth-service:3.5.4
        ports:
        - containerPort: 6268
        resources:
          requests:
            memory: "64Mi"
            cpu: "500m"
