apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: travelduty
spec:
  replicas: 5
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
      - name: auth-service
        image: travelduty/auth-service:2.1.7
        ports:
        - containerPort: 6677
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
