apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: travelduty
spec:
  replicas: 4
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
      - name: auth-service
        image: travelduty/auth-service:4.4.6
        ports:
        - containerPort: 5292
        resources:
          requests:
            memory: "64Mi"
            cpu: "500m"
