apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: travelduty
spec:
  replicas: 4
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: travelduty/backend:1.3.9
        ports:
        - containerPort: 7520
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
