apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: travelduty
spec:
  replicas: 5
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: travelduty/backend:4.9.0
        ports:
        - containerPort: 6739
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
