apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: travelduty
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: travelduty/backend:2.5.8
        ports:
        - containerPort: 5615
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
