apiVersion: apps/v1
kind: Deployment
metadata:
  name: booking-service
  namespace: travelduty
spec:
  replicas: 1
  selector:
    matchLabels:
      app: booking-service
  template:
    metadata:
      labels:
        app: booking-service
    spec:
      containers:
      - name: booking-service
        image: travelduty/booking-service:5.3.5
        ports:
        - containerPort: 7289
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
