apiVersion: apps/v1
kind: Deployment
metadata:
  name: booking-service
  namespace: travelduty
spec:
  replicas: 5
  selector:
    matchLabels:
      app: booking-service
  template:
    metadata:
      labels:
        app: booking-service
    spec:
      containers:
      - name: booking-service
        image: travelduty/booking-service:4.5.7
        ports:
        - containerPort: 6623
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
