apiVersion: apps/v1
kind: Deployment
metadata:
  name: booking-service
  namespace: travelduty
spec:
  replicas: 2
  selector:
    matchLabels:
      app: booking-service
  template:
    metadata:
      labels:
        app: booking-service
    spec:
      containers:
      - name: booking-service
        image: travelduty/booking-service:3.3.7
        ports:
        - containerPort: 7441
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
