apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: travelduty
spec:
  replicas: 4
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: travelduty/frontend:3.0.2
        ports:
        - containerPort: 5619
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
