apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: travelduty
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: travelduty/frontend:1.5.5
        ports:
        - containerPort: 7179
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
