apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: travelduty
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: travelduty/nginx:3.7.5
        ports:
        - containerPort: 6580
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
