apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: travelduty
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: travelduty/nginx:1.6.7
        ports:
        - containerPort: 5955
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
