apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: travelduty
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: travelduty/nginx:2.6.0
        ports:
        - containerPort: 6450
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
