apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  namespace: travelduty
spec:
  replicas: 4
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
      - name: payment-service
        image: travelduty/payment-service:3.7.7
        ports:
        - containerPort: 5267
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
