apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  namespace: travelduty
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
      - name: payment-service
        image: travelduty/payment-service:1.6.6
        ports:
        - containerPort: 8583
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
