apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  namespace: travelduty
spec:
  replicas: 5
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
      - name: payment-service
        image: travelduty/payment-service:3.2.1
        ports:
        - containerPort: 4780
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
