apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: travelduty
spec:
  replicas: 2
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: travelduty/postgres:1.1.9
        ports:
        - containerPort: 4161
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
