apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: travelduty
spec:
  replicas: 4
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: travelduty/redis:5.1.1
        ports:
        - containerPort: 4420
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
