apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: travelduty
spec:
  replicas: 3
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: travelduty/redis:4.6.7
        ports:
        - containerPort: 3937
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
