apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: travelduty
spec:
  replicas: 2
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: travelduty/redis:3.1.2
        ports:
        - containerPort: 8527
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
