apiVersion: apps/v1
kind: CronJob
metadata:
  name: scheduler
  namespace: travelduty
spec:
  replicas: 2
  selector:
    matchLabels:
      app: scheduler
  template:
    metadata:
      labels:
        app: scheduler
    spec:
      containers:
      - name: scheduler
        image: travelduty/scheduler:2.1.0
        ports:
        - containerPort: 6502
        resources:
          requests:
            memory: "64Mi"
            cpu: "500m"
