apiVersion: apps/v1
kind: CronJob
metadata:
  name: scheduler
  namespace: travelduty
spec:
  replicas: 3
  selector:
    matchLabels:
      app: scheduler
  template:
    metadata:
      labels:
        app: scheduler
    spec:
      containers:
      - name: scheduler
        image: travelduty/scheduler:4.2.4
        ports:
        - containerPort: 8973
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
