apiVersion: apps/v1
kind: CronJob
metadata:
  name: scheduler
  namespace: travelduty
spec:
  replicas: 5
  selector:
    matchLabels:
      app: scheduler
  template:
    metadata:
      labels:
        app: scheduler
    spec:
      containers:
      - name: scheduler
        image: travelduty/scheduler:1.3.6
        ports:
        - containerPort: 3527
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
