apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: travelduty
spec:
  replicas: 4
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: worker
        image: travelduty/worker:3.7.9
        ports:
        - containerPort: 6758
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
