apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: travelduty
spec:
  replicas: 5
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: worker
        image: travelduty/worker:4.4.3
        ports:
        - containerPort: 5292
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
