apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: travelduty
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: worker
        image: travelduty/worker:2.1.2
        ports:
        - containerPort: 6997
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
